### ISSUE TITLE
Napari-plugin

### ISSUE THREAD

**Issue by haesleinhuepf** [yfukai/laptrack#295]
Hi @yfukai ,

this is just to let you know that I started a [napari-laptrack](https://github.com/haesleinhuepf/napari-laptrack) plugin which uses LapTrack as dependency. It has just basic functionality yet. I'm planning to expand it iteratively based on collaborations; implementing what people need. In case you would like to collaborate on this, just let me know. Contributions (issues, PRs) are welcome. I'm also happy to share write-access to github and pypi repositories if that's of interest for you. Otherwise, it's fine, too. I'm happy to maintain it alone. No pressure. May I just ask for one little thing: In case you update LapTrack and break backwards compatibility, consider letting me know by [creating an issue](https://github.com/haesleinhuepf/napari-laptrack/issues). 

Big thanks for programming LapTrack! It's awesome.

Best,
Robert

P.S.: Feel free to close this issue; it's just a notification anyway 🙂

**Comment by yfukai** [comment]
Thanks @haesleinhuepf, it's more than great to hear you've started working on that! I've been thinking about making a plugin or contributing to the arboretum but haven't been able to with other projects. I'm happy to contribute to the repo whenever I have time. 
About the API, I think I should make a major release at some point (maybe when the napari plugin becomes stable) and I'll follow the semantic versioning after that. I'm also happy to get feedback for this package itself.
Cheers,
