### ISSUE TITLE
`calc_scores` assumes overlapping tracks share a `track-id`

### ISSUE THREAD

**Issue by DragaDoncila** [yfukai/laptrack#374]
Hello, I've been using `laptrack` to generate tracks for some cell tracking challenge data, and I wanted to compute the TE and TP scores using the `calc_scores` function. However, I realized the `calc_scores` function was finding fewer overlapping tracks than expected, and after looking at the implementation and the tests, I think it's because it expects that `track-id` is the same in ground truth and predicted tracks. 

For example, if I change the current `pred_tree` in `test_scores.py` by swapping track indices 1 and 2, all the tests fail, even though the graph and the tracks are exactly the same:

```python
    pred_tree = nx.from_edgelist(
        [
            ((0, 0), (1, 0)),
            ((1, 0), (2, 0)),
            ((2, 0), (3, 0)),
            ((4, 0), (5, 0)),
            ((2, 0), (3, 2)), # 1
            ((1, 2), (2, 1)), # 2
            ((2, 2), (3, 1)), # 2
            ((3, 2), (4, 2)), # 1
            ((4, 1), (5, 2)), # 1
        ]
    )
```

It's possible I'm misunderstanding how to use the function, but I would've expected that as long as the tracks overlap, it wouldn't matter what integer value was assigned to the `track-id`. Otherwise, it seems like some track id matching is required?

Please let me know if I've misunderstood anything!

**Comment by yfukai** [comment]
Hi @DragaDoncila thanks for the report! If I understand correctly, there seems to be a misunderstanding on the input for `calc_scores.` The function takes the `((frame1,index1), (frame2,index2))`-type of the input, where `index` is the index in `coords` of [`predict` function](https://laptrack.readthedocs.io/en/stable/reference.html#laptrack.LapTrack.predict) (not `track_id`). Swapping the index changes the input track tree as the attached figure, so I believe it's natural that the test fails. 
![IMG_4977](https://github.com/yfukai/laptrack/assets/5919272/f8d8069e-b6c6-4eec-bf01-06a7bfda6425)

Hopefully [this function](https://laptrack.readthedocs.io/en/stable/reference.html#laptrack.data_conversion.convert_dataframe_to_coords_frame_index) helps conversion from the dataframe with `track_id` to the input, but we may need a better way (unfortunately I cannot take time for this for a while but the repo is very welcome for a pull request).

Please let me know if I'm misunderstanding your points. Thanks!

**Comment by yfukai** [comment]
Hi @DragaDoncila, I found https://github.com/Janelia-Trackathon-2023/traccuracy which has a similar purpose. Do you think it makes sense to transfer my metric routines to that package?

**Comment by DragaDoncila** [comment]
Hi @yfukai - thank you for the detailed response - and sorry for the delay in mine! I haven't had a chance to convert my solution into the right format and try `calc_scores` again, but it's clear that I did misunderstand its use - sorry for the noise! 

> Do you think it makes sense to transfer my metric routines to that package? I'm happy to provide a help if necessary.

I've been thinking about this. I think it would be awesome to have TP and TE implemented in `traccuracy` - it seems to me a great extension of [TF](https://github.com/Janelia-Trackathon-2023/traccuracy/issues/40), which we already want to implement. We've tried to structure the package to make it easy to add new metrics, but we're still making changes to the API and overall composition - this would be a great opportunity for us to stress test things with another use case. 

If you're interested in contributing yourself I'd be happy to catch up in more detail about how we can leverage the code you've already got here!

**Comment by yfukai** [comment]
Thanks @DragaDoncila for your reply! I was thinking it may ease the development if we use the test data and the implementation in `traccuracy`. I'm definitely happy to contribute to this as my weekend project. I'll walk through the documentation and code, but it would be helpful if you could let me know possible starting point. Thanks!

**Comment by DragaDoncila** [comment]
Hello, would definitely love to help you get started - our docs and API are still quite fluid and not that complete so I'm happy to provide guidance as needed.

In general we've tried to structure the metrics compute pipeline into 

`Loaders -> Matchers -> Metrics`

`Loaders` bring tracking data into memory into our `TrackingGraph` object.
`Matchers` create a correspondence between each node in the GT and each node in the predicted data. I think, from looking at the `predict` function, that this part is implicit for your implementation of the `calc_scores` function i.e. you expect that the coords of the GT and the coords of the predicted data are identical, and this allows you to assume that a point index in GT is the same point as that index in predicted data? If so, then this will be the starting point for us is figuring out what matching strategy makes sense for this metric. I think any of our current matchers could be used for "blob like" data, but we don't have a matcher yet for point data - although we have an [issue](https://github.com/Janelia-Trackathon-2023/traccuracy/issues/31) already. But, I think you should write your metric assuming the matching is already complete.
`Metrics` use the mapping created during the matching step as the correspondence between GT and pred, and compute whatever metrics they wish. I think you could just add your metric function as a new metric. The only question then would be what kind of matching these metrics support: just one-to-one gt to pred? Could two predicted nodes be matched to one single GT node?

**Comment by yfukai** [comment]
Hi @DragaDoncila, thanks for your comment and I'm sorry for the late response. I now got started to work on this! 

Those metrics require a criterion to "assign" the coords of the ground-truth tracks to those of the predicted ones. I believe this is done by `Matchers`. According to the definition, I believe it is OK to have more than two predicted nodes on the single GT node (copied from [my paper](https://academic.oup.com/bioinformatics/article/39/1/btac799/6887138)):

- TE for a single ground truth track $T^g_j$ is calculated by finding the predicted track $T^p_k$ that **overlaps with** $T^g_j$ in the largest number of the frames and then dividing the overlap frame counts by the total frame counts for $T^g_j$. The TE for the total dataset is calculated as the mean of TEs for all ground truth tracks, weighted by the length of the tracks.

- TP is defined analogously, with $T^g_j$ and $T^p_k$ being swapped in the definition.

I'll check the code for other `Metrics` and implement the TE and TP!

**Comment by yfukai** [comment]
I made a pull request here!
https://github.com/Janelia-Trackathon-2023/traccuracy/pull/112
Please let me close this issue for now.
