### ISSUE TITLE
Assertion error with: convert_dataframe_to_coords_frame_index

### ISSUE THREAD

**Issue by piango** [yfukai/laptrack#405]
Hello

I am new to your cool work here.

I am doing some 3D tracking (in time) of some labeled images.

I am trying some preliminary runs with your example @ [laptrack](https://github.com/yfukai/laptrack/tree/main)/[docs](https://github.com/yfukai/laptrack/tree/main/docs)/[examples](https://github.com/yfukai/laptrack/tree/main/docs/examples)
/3D_tracking.ipynb

And I get an **AssertionError** at:

   track_df, split_df, merge_df = lt.predict_dataframe(

  File ~\.conda\envs\tracking\Lib\site-packages\laptrack\_tracking.py:763 in predict_dataframe
    coords, frame_index = convert_dataframe_to_coords_frame_index(

  File ~\.conda\envs\tracking\Lib\site-packages\laptrack\data_conversion.py:81 in convert_dataframe_to_coords_frame_index
    coords = convert_dataframe_to_coords(

  File ~\.conda\envs\tracking\Lib\site-packages\laptrack\data_conversion.py:45 in convert_dataframe_to_coords
    assert np.array_equal(np.arange(df[frame_col].max() + 1), [g[0] for g in grps])

I am not an expert here. But i would like to get some idea on where this could be going wrong.
In the labels are not always continuous, meaning that in some frames some labels are not present and so on. so there is not a good trajectory like you have your example.

Hope this is enough information.

Thanks
:)

**Comment by yfukai** [comment]
Hi @piango, thanks for the report! Unfortunately the error message is not clear, but I suspect that this is because there's a frame without any points in the input dataframe. Let me try to see if there's a way to make it possible to track points even with this condition.

**Comment by piango** [comment]
Hi,

thanks for your response.
in the mean time i can try to see if the cause is due to some frames missing labels.

i will let u know soon.
thank you

**Comment by piango** [comment]
Hi
I just checked. 
I removed the frames without any labels. and the workflow example you posted (that I am testing) works well.
So it is the issue.
It would be great if I can still use your pipeline, even if some frames are missing labels.
But its not a priority, and I can understand if you are busy.

:)

**Comment by yfukai** [comment]
Now it should work with a frame without points! @piango
