### ISSUE TITLE
laptrack uses scikit-image 0.19

### ISSUE THREAD

**Issue by drchrisch** [yfukai/laptrack#427]
Hello @yfukai,

laptrack uses scikit-image version 0.19. Is there a special reason for this or would it also work with 0.22.* or higher?

Best,
drchrisch

**Comment by yfukai** [comment]
Hi thanks @drchrisch for your question, I remember there was some issue with `scipy` version with the higher version. For example https://github.com/yfukai/laptrack/actions/runs/9110598653/job/25045962509 . 
Do you have any idea on how to solve this issue?

**Comment by drchrisch** [comment]
No, I'm afraid that's beyond my knowledge. I came across the version settings because I was trying to add laptrack to an environment (python 3.9) that had scikit-image set to 0.22.*. It works with minor tweaks to my code.
Thanks

**Comment by yfukai** [comment]
I think I managed to solve the problem. It will work with `scikit-image>=0.20.0,<1.0.0` if `python>=3.11` after merging PR #428. Please be patient until the patch release.
